### ISSUE TITLE
Starter decks

### ISSUE THREAD

**Issue by Liwott** [onpon4/kotc#10]
Not really an issue, sorry if this is not the right place to ask.
Are there some typical decks that a beginner can take to start playing right away before building their own decks?

**Comment by onpon4** [comment]
I haven't put any together, but it's a good idea! Maybe for 11th Edition I should take a look at the decks I've created and put such a thing together as "sets". (I have a holy deck, a satanic deck, a direct damage deck, a destruction deck, and a resurrection deck. I also have a Yu-Gi-Oh fandeck but can't publish that for obvious copyright reasons.)

EDIT: By the way, suggestions are absolutely an appropriate use of the issue system, so no worries. 🙂

🕵️

**Comment by onpon4** [comment]
I'm happy to report that with the release of [11th Edition](https://github.com/kotc-game/kotc/releases/tag/v11.0), we now have two starter decks! :slightly_smiling_face: 

🕷️
