### ISSUE TITLE
Mistaken costs?

### ISSUE THREAD

**Issue by Liwott** [onpon4/kotc#9]
When computing the costs of the cards in the cards-png folder, I disagree about 3 cards : 

#### Bloodborne Transmission
Instead of 6 I find : 4x1x2 - 4x1 = 4

#### Show of Aggression
Instead of 3 I find : 3x2/2 - 1 = 2

#### Spirit Board
Instead of 4 I find : 0+10/5-2+(2x1/2)+(2x3-2x2)+(2x3-2x2)=5

**Comment by onpon4** [comment]
Wow, I never expected this. Thanks for the corrections! Did calculations on my end and I concur, the costs listed on these cards were wrong. I really ought to develop that card generation program I want to develop at some point. Would help avoid mistakes like these. EDIT: I just noticed your CardCreationForTheKeeper project, that's very interesting! Will definitely be keeping an eye on that, maybe I'll be able to contribute some to it.

🕵️

**Comment by Liwott** [comment]
Thanks for the quick reaction! Btw you may want to update the "set" files as well.

Still have to actually try the game (I want to translate cards in French first, which was one of my main motivations for writing that tool), but I like very much the core concept of a free CCG!

**Comment by onpon4** [comment]
Thanks! I'm glad you like it! Yes, the set files will need an update too. I'll do that after all the cards have been brought fully up-to-date. (Some costs changed as of 11th edition and a lot of cards have outdated costs as a result; I just updated Anubis for this reason and there's a bunch more to go, may take awhile. Yet another reason a tool that does this automatically would be nice. 😅)

🕵️
